In [0]:
!pip install kmodes

Collecting kmodes
  Downloading https://files.pythonhosted.org/packages/79/c0/f7d8a0eb41ac6f302b4bc100f91b6e0f2558425ccfefaa0ec0430f77ee97/kmodes-0.10.1-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.6/dist-packages (from kmodes) (1.16.4)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from kmodes) (0.13.2)
Requirement already satisfied: scipy>=0.13.3 in /usr/local/lib/python3.6/dist-packages (from kmodes) (1.3.0)
Requirement already satisfied: scikit-learn>=0.19.0 in /usr/local/lib/python3.6/dist-packages (from kmodes) (0.21.2)
Installing collected packages: kmodes
Successfully installed kmodes-0.10.1

In [0]:
import numpy as np
from kmodes.kmodes import KModes
import pandas as pd
import os
import pandas_profiling
from sklearn import preprocessing
from numpy import array
from numpy import argmax
from sklearn
import math
from mpl_toolkits.mplot3d import Axes3D

In [0]:
train=pd.read_excel("Data_Train.xlsx")
test=pd.read_excel("Data_Test.xlsx")

In [0]:
print(train.info())
print(test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
Name                 6019 non-null object
Location             6019 non-null object
Year                 6019 non-null int64
Kilometers_Driven    6019 non-null int64
Fuel_Type            6019 non-null object
Transmission         6019 non-null object
Owner_Type           6019 non-null object
Mileage              6017 non-null object
Engine               5983 non-null object
Power                5983 non-null object
Seats                5977 non-null float64
New_Price            824 non-null object
Price                6019 non-null float64
dtypes: float64(2), int64(2), object(9)
memory usage: 611.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 12 columns):
Name                 1234 non-null object
Location             1234 non-null object
Year                 1234 non-null int64
Kilometers_Driven    1234 non-null int64
Fuel_Type            1234 non-null object
Transmission         1234 non-null object
Owner_Type           1234 non-null object
Mileage              1234 non-null object
Engine               1224 non-null object
Power                1224 non-null object
Seats                1223 non-null float64
New_Price            182 non-null object
dtypes: float64(1), int64(2), object(9)
memory usage: 115.8+ KB
None

In [0]:
print(train.columns)

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='object')

In [0]:
cols=['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price']

7253

In [0]:
train=res1asd

In [0]:
eda_Report

In [0]:
pandas_profiling.ProfileReport(train)

In [0]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.6/dist-packages (3.2.5)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from nltk) (1.12.0)

In [0]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [0]:
#train["Name"]=train["Name"].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
tfidf=TfidfVectorizer(min_df=2,max_df=0.5,ngram_range=(1,2))
train["Name"]=train["Name"].astype(str)
features=tfidf.fit(train["Name"])
measures=features.transform(train["Name"])

df=pd.DataFrame(
measures.todense(),
columns=tfidf.get_feature_names())
df.head()

    05  05 revotorq   0d   0l  ...  zxi optional  zxi plus  zxi tdci  zxi with
0  0.0          0.0  0.0  0.0  ...           0.0       0.0       0.0       0.0
1  0.0          0.0  0.0  0.0  ...           0.0       0.0       0.0       0.0
2  0.0          0.0  0.0  0.0  ...           0.0       0.0       0.0       0.0
3  0.0          0.0  0.0  0.0  ...           0.0       0.0       0.0       0.0
4  0.0          0.0  0.0  0.0  ...           0.0       0.0       0.0       0.0

[5 rows x 2389 columns]

In [0]:
df.columns

Index(['05', '05 revotorq', '0d', '0l', '0l 2wd', '0l 4x4', '0l crdi',
       '0l diesel', '0l portfolio', '0l tdi',
       ...
       'zxi at', 'zxi bsiii', 'zxi duratec', 'zxi leather', 'zxi mt',
       'zxi option', 'zxi optional', 'zxi plus', 'zxi tdci', 'zxi with'],
      dtype='object', length=2389)

In [0]:
data=df

In [0]:
wcss=[]

In [0]:
for i in range(1,20):
  kmeans=KMeans(n_clusters=i,max_iter=300,n_init=10,random_state=0)
  kmeans.fit(data)
  wcss.append(kmeans.inertia_)

In [0]:
plt.plot(range(1,20),wcss)
plt.title("The Elbow Method")
plt.xlabel("number cluster")
plt.ylabel("cluster elbow value")

ValueError: ignored

In [0]:
plt.show()

In [0]:
plt.savefig("wcss.pnd")

In [0]:
kmeans=KMeans(n_clusters=17,max_iter=300,n_init=10,random_state=0)

In [0]:
kmeans=kmeans.fit(data)

In [0]:
clustered_name=kmeans.predict(data)

In [0]:
clustered_name

array([ 0, 11,  4, ...,  8, 14,  6], dtype=int32)

In [0]:
train["Name"]=clustered_name

In [0]:
train["Location"].unique()

array(['Mumbai', 'Pune', 'Chennai', 'Coimbatore', 'Hyderabad', 'Jaipur',
       'Kochi', 'Kolkata', 'Delhi', 'Bangalore', 'Ahmedabad'],
      dtype=object)

In [0]:
#location={'Mumbai':1, 'Pune':2, 'Chennai':3, 'Coimbatore':4, 'Hyderabad':5, 'Jaipur':6,
#       'Kochi':7, 'Kolkata':8, 'Delhi':9, 'Bangalore':10, 'Ahmedabad':11}

In [0]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [0]:
lb1=lb.fit(train["Location"])

In [0]:
train["Location"]=lb1.transform(train["Location"])

In [0]:
lb2=lb.fit(train["Fuel_Type"])

In [0]:
train["Fuel_Type"]=lb2.transform(train["Fuel_Type"])

In [0]:
lb3=lb.fit(train["Transmission"])

In [0]:
train["Transmission"]=lb3.transform(train["Transmission"])

In [0]:
lb4=lb.fit(train["Owner_Type"])

In [0]:
train["Owner_Type"]=lb4.transform(train["Owner_Type"])

In [0]:
vl=train["Mileage"].str.replace("km/kg","",case=False)

In [0]:
vl=vl.str.replace("kmpl","",case=False)

In [0]:
type(vl)

pandas.core.series.Series

In [0]:
vl.unique()

array(['26.6 ', '19.67 ', '18.2 ', '20.77 ', '15.2 ', '21.1 ', '23.08 ',
       '11.36 ', '20.54 ', '22.3 ', '21.56 ', '16.8 ', '25.2 ', '12.7 ',
       '0.0 ', '13.5 ', '25.8 ', '28.4 ', '20.45 ', '14.84 ', '22.69 ',
       '23.65 ', '13.53 ', '18.5 ', '14.4 ', '20.92 ', '17.5 ', '12.8 ',
       '19.01 ', '14.53 ', '11.18 ', '12.4 ', '16.09 ', '14.0 ', '24.3 ',
       '18.15 ', '11.74 ', '22.07 ', '19.7 ', '25.4 ', '25.32 ', '14.62 ',
       '14.28 ', '14.9 ', '11.25 ', '24.4 ', '16.55 ', '17.11 ', '22.9 ',
       '17.8 ', '18.9 ', '15.04 ', '25.17 ', '20.36 ', '13.29 ', '13.68 ',
       '20.0 ', '15.8 ', '25.0 ', '16.4 ', '24.52 ', '22.1 ', '8.5 ',
       '15.1 ', '16.95 ', '19.64 ', '16.5 ', '18.53 ', '17.57 ', '18.0 ',
       '23.2 ', '16.73 ', '17.0 ', '13.0 ', '17.68 ', '22.7 ', '16.2 ',
       '15.26 ', '23.0 ', '19.83 ', '14.94 ', '17.71 ', '14.74 ', '16.0 ',
       '22.32 ', '12.99 ', '23.3 ', '19.15 ', '10.8 ', '15.0 ', '22.0 ',
       '21.9 ', '12.05 ', '11.7 ', '21.21 ', '20.73 ', '24.07 ', '19.0 ',
       '20.58 ', '19.27 ', '11.5 ', '18.6 ', '21.14 ', '11.05 ', '21.76 ',
       '7.81 ', '21.66 ', '17.2 ', '20.63 ', '19.4 ', '14.8 ', '26.0 ',
       '20.4 ', '21.5 ', '15.3 ', '17.9 ', '16.6 ', '22.54 ', '25.44 ',
       '13.7 ', '22.48 ', '12.9 ', '19.98 ', '21.4 ', '19.81 ', '15.4 ',
       '25.47 ', '19.87 ', '17.45 ', '14.7 ', '15.64 ', '15.73 ',
       '23.59 ', '16.1 ', '27.4 ', '20.46 ', '15.29 ', '20.51 ', '11.8 ',
       '14.3 ', '14.67 ', '17.19 ', '21.03 ', '22.5 ', '16.82 ', '11.72 ',
       '17.4 ', '17.05 ', '24.0 ', '28.09 ', '20.5 ', '13.1 ', '19.91 ',
       '18.7 ', '16.38 ', '11.57 ', '17.3 ', '22.95 ', '18.88 ', '23.4 ',
       '22.74 ', '12.07 ', '17.1 ', '18.48 ', '16.47 ', '23.1 ', '14.07 ',
       '16.02 ', '19.3 ', '17.7 ', '9.52 ', '14.75 ', '26.3 ', '11.3 ',
       '21.12 ', '21.02 ', '14.45 ', '19.33 ', '13.8 ', '24.7 ', '11.0 ',
       '11.07 ', '21.43 ', '14.21 ', '18.86 ', '16.07 ', '13.49 ',
       '20.38 ', '12.0 ', '17.01 ', '13.2 ', '20.37 ', '15.96 ', '14.16 ',
       '13.17 ', '27.62 ', '25.1 ', '15.17 ', '11.33 ', '17.92 ',
       '12.55 ', '12.6 ', '17.72 ', '18.16 ', '15.68 ', '15.5 ', '12.1 ',
       '14.83 ', '17.6 ', '14.6 ', '14.66 ', '10.93 ', '20.68 ', '9.9 ',
       '21.13 ', '20.14 ', '19.2 ', '27.3 ', '16.36 ', '26.59 ', '12.5 ',
       '13.6 ', '15.06 ', '10.13 ', '17.21 ', '15.97 ', '10.5 ', '14.69 ',
       '23.9 ', '19.1 ', '21.27 ', '15.9 ', '20.7 ', '14.1 ', '20.89 ',
       '18.12 ', '12.3 ', '19.71 ', '9.43 ', '13.4 ', '13.14 ', '18.1 ',
       '22.77 ', '14.49 ', '12.39 ', '10.91 ', '20.85 ', '15.63 ',
       '27.39 ', '18.3 ', '16.78 ', '25.5 ', '10.0 ', '13.73 ', '24.2 ',
       '14.02 ', '26.83 ', '16.77 ', '24.5 ', '20.34 ', '21.7 ', '9.7 ',
       '14.33 ', '21.64 ', '19.16 ', '16.93 ', '9.0 ', '26.2 ', '16.3 ',
       '12.62 ', '20.64 ', '14.24 ', '18.06 ', '10.2 ', '10.1 ', '18.25 ',
       '13.93 ', '25.83 ', '8.6 ', '13.24 ', '17.09 ', '23.84 ', '8.45 ',
       '19.6 ', '19.5 ', '20.3 ', '16.05 ', '11.2 ', '27.03 ', '18.78 ',
       '12.35 ', '14.59 ', '17.32 ', '14.95 ', '13.22 ', '23.03 ',
       '33.44 ', '15.6 ', '19.12 ', '10.98 ', '33.54 ', '16.46 ', '18.4 ',
       '11.1 ', '13.01 ', '18.8 ', '16.52 ', '18.44 ', '19.49 ', '23.5 ',
       '23.8 ', '12.65 ', '20.65 ', '21.72 ', '12.19 ', '26.1 ', '18.33 ',
       '12.81 ', '17.06 ', '17.67 ', '19.34 ', '8.3 ', '16.96 ', '11.79 ',
       '20.86 ', '16.98 ', '11.68 ', '15.74 ', '15.7 ', '18.49 ', '10.9 ',
       '19.59 ', '11.4 ', '13.06 ', '21.0 ', '15.15 ', '16.9 ', '18.23 ',
       '17.16 ', '17.43 ', '19.08 ', '18.56 ', '11.9 ', '24.6 ', '21.79 ',
       '12.95 ', '25.6 ', '13.45 ', '26.21 ', '13.58 ', '16.25 ', '10.4 ',
       '17.44 ', '22.71 ', '17.54 ', '15.87 ', '9.5 ', '11.56 ', '14.39 ',
       '19.09 ', '17.85 ', '31.79 ', '18.18 ', '21.19 ', '21.8 ',
       '15.42 ', '14.47 ', '19.69 ', '12.83 ', '8.0 ', '22.8 ', '12.63 ',
       '14.57 ', '27.28 ', '15.41 ', '32.26 ', '18.19 ', '13.33 ',
       '16.7 ', '17.84 ', '23.19 ', '11.49 ', '18.51 ', '13.44 ', '8.7 ',
       '8.77 ', '17.97 ', '23.57 ', '12.37 ', '9.1 ', '12.51 ', '19.44 ',
       '21.38 ', '16.51 ', '24.8 ', '14.42 ', '26.8 ', '24.04 ', '9.8 ',
       '19.68 ', '21.2 ', '19.72 ', '14.2 ', '12.98 ', '23.01 ', '16.12 ',
       '9.3 ', '15.85 ', nan, '17.88 ', '10.6 ', '11.78 ', '7.94 ',
       '25.01 ', '8.1 ', '13.9 ', '11.62 ', '20.62 ', '15.11 ', '10.37 ',
       '18.59 ', '9.74 ', '14.81 ', '8.2 ', '12.97 ', '7.5 ', '30.46 ',
       '6.4 ', '12.85 ', '18.69 ', '17.24 ', '13.07 ', '12.2 ', '20.8 ',
       '11.88 ', '12.08 ', '15.56 ', '14.5 ', '17.15 '], dtype=object)

In [0]:
vl=vl.astype(float)

In [0]:
train["Mileage"]=vl

In [0]:
train.head()

   Name  Location  Year  ...      Power  Seats  New_Price
0     0         9  2010  ...  58.16 bhp    5.0        NaN
1    11        10  2015  ...  126.2 bhp    5.0        NaN
2     4         2  2011  ...   88.7 bhp    5.0  8.61 Lakh
3     0         2  2012  ...  88.76 bhp    7.0        NaN
4    12         3  2013  ...  140.8 bhp    5.0        NaN

[5 rows x 12 columns]

In [0]:
vl=train["Engine"].str.replace("CC","",case=False)

In [0]:
vl=vl.astype(float)

In [0]:
train["Engine"]=vl

In [0]:
vl=train["Power"].str.replace("bhp","",case=False)

In [0]:
vl=vl.str.replace("null","0.0",case=False)

In [0]:
vl=vl.astype(float)

In [0]:
train["Power"]=vl

In [0]:
train["Seats"]=train["Seats"].fillna(0)

In [0]:
vl=train["New_Price"].str.replace("Lakh","",case=False)

In [0]:
vl=vl.str.replace("Cr","",case=False)

In [0]:
vl=vl.fillna('0.0')

In [0]:
vl=vl.astype(float)

In [0]:
train["New_Price"]=vl

In [0]:
train.head()

   Name  Location  Year  Kilometers_Driven  ...  Engine   Power  Seats  New_Price
0     0         9  2010              72000  ...   998.0   58.16    5.0       0.00
1    11        10  2015              41000  ...  1582.0  126.20    5.0       0.00
2     4         2  2011              46000  ...  1199.0   88.70    5.0       8.61
3     0         2  2012              87000  ...  1248.0   88.76    7.0       0.00
4    12         3  2013              40670  ...  1968.0  140.80    5.0       0.00

[5 rows x 12 columns]

In [0]:
len(train)

7253

In [0]:
train.to_excel("preprocessed.xlsx")

In [0]:
from sklearn import preprocessing

x = data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(train)
df = pd.DataFrame(x_scaled)

In [0]:
df.head()

       0    1         2         3   ...        8         9    10        11
0  0.0000  0.9  0.608696  0.011051  ...  0.156261  0.094416  0.5  0.000000
1  0.6875  1.0  0.826087  0.006282  ...  0.254809  0.204870  0.5  0.000000
2  0.2500  0.2  0.652174  0.007051  ...  0.190179  0.143994  0.5  0.086169
3  0.0000  0.2  0.695652  0.013359  ...  0.198448  0.144091  0.7  0.000000
4  0.7500  0.3  0.739130  0.006231  ...  0.319946  0.228571  0.5  0.000000

[5 rows x 12 columns]

In [0]:
print(len(df),len(test),len(Y))

7253 1234 6019

In [0]:
vl=len(df)-len(test)
vl

6019

In [0]:
X_test=df.iloc[vl:]
len(X_test)
X_test.head()

          0    1         2         3   ...        8         9    10        11
6019  0.8125  0.4  0.782609  0.006271  ...  0.156261  0.094481  0.4  0.000000
6020  0.8125  0.3  0.739130  0.008357  ...  0.122173  0.076786  0.5  0.000000
6021  0.0625  0.9  0.913043  0.005205  ...  0.391664  0.239935  0.7  0.252902
6022  0.5625  0.5  0.695652  0.021359  ...  0.218022  0.000000  0.5  0.000000
6023  0.1250  0.9  0.782609  0.004435  ...  0.189841  0.134497  0.5  0.000000

[5 rows x 12 columns]

In [0]:
X_train=df[:len(df)-len(test)]
print(len(X_train),len(Y))
X_train.head()

6019 6019

       0    1         2         3   ...        8         9    10        11
0  0.0000  0.9  0.608696  0.011051  ...  0.156261  0.094416  0.5  0.000000
1  0.6875  1.0  0.826087  0.006282  ...  0.254809  0.204870  0.5  0.000000
2  0.2500  0.2  0.652174  0.007051  ...  0.190179  0.143994  0.5  0.086169
3  0.0000  0.2  0.695652  0.013359  ...  0.198448  0.144091  0.7  0.000000
4  0.7500  0.3  0.739130  0.006231  ...  0.319946  0.228571  0.5  0.000000

[5 rows x 12 columns]

In [0]:
X_train=X_train.fillna(0.0)

In [0]:
from sklearn.linear_model import LinearRegression
regressor_model=LinearRegression()

In [0]:
regressor_model=regressor_model.fit(X_train,Y)

In [0]:
X_test=X_test.fillna(0.0)

In [0]:
X_test.head()

          0    1         2         3   ...        8         9    10        11
6019  0.8125  0.4  0.782609  0.006271  ...  0.156261  0.094481  0.4  0.000000
6020  0.8125  0.3  0.739130  0.008357  ...  0.122173  0.076786  0.5  0.000000
6021  0.0625  0.9  0.913043  0.005205  ...  0.391664  0.239935  0.7  0.252902
6022  0.5625  0.5  0.695652  0.021359  ...  0.218022  0.000000  0.5  0.000000
6023  0.1250  0.9  0.782609  0.004435  ...  0.189841  0.134497  0.5  0.000000

[5 rows x 12 columns]

In [0]:
y_pred=regressor_model.predict(X_test)

In [0]:
Y.unique()

array([ 1.75, 12.5 ,  4.5 , ...,  2.27, 17.56,  7.43])

In [0]:
submission=pd.DataFrame()
submission["Price"]=y_pred
submission.to_excel("output_linear.xlsx")